import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Script from "next/script";
import AccessibilityClientProvider from "../components/AccessibilityClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <a
          href="#main-content"
          style={{
            position: "absolute",
            left: 0,
            top: 0,
            background: "#fff",
            color: "#4f46e5",
            padding: 8,
            zIndex: 200,
            transform: "translateY(-120%)",
            transition: "transform 0.2s",
          }}
        >
          Skip to content
        </a>
        <AccessibilityClientProvider>
          <Header />
          <div id="main-content" style={{ flex: 1 }}>
            {children}
          </div>
          <Footer />
        </AccessibilityClientProvider>
        <Script
          strategy="afterInteractive"
          data-domain="learnova.app"
          src="https://plausible.io/js/plausible.js"
        />
      </body>
    </html>
  );
}
